export const sym = [
  "abdominal cramp",
  "abdominal distention",
  "abnormal behavior",
  "abnormal bleeding",
  "abnormal sensation",
  "abnormally frequent",
  "abscess",
  "aching",
  "acne",
  "acquiring drinking alcohol taking lot time",
  "affected part turning white",
  "anemia",
  "anxiety",
  "arm",
  "attack pain",
  "back",
  "bacterial infection",
  "bad breath",
  "bad smelling thin vaginal discharge",
  "bad smelling vaginal discharge",
  "barky cough",
  "belching",
  "better sitting worse lying",
  "birth baby younger week gestational age",
  "bleeding gum",
  "bleeding skin",
  "blindness",
  "blindness one eye",
  "blister sunlight",
  "bloating",
  "blood stool",
  "blood urine",
  "bloody diarrhea",
  "blue",
  "bluish skin coloration",
  "blurred vision",
  "blurry vision",
  "body tremor",
  "bone pain",
  "bowed leg",
  "breakdown skeletal muscle",
  "breathing problem",
  "bruising",
  "burning",
  "burning redness eye",
  "burning stabbing pain",
  "burning urination",
  "certain thought repeatedly",
  "change bowel movement",
  "change breast shape",
  "change color",
  "change hair",
  "change reflex",
  "change skin color red black",
  "change sleeping eating pattern",
  "change taste",
  "change voice",
  "characteristic facial feature",
  "characteristic rash",
  "chest discomfort",
  "chest pain",
  "chest tightness",
  "chill",
  "chronic cough",
  "chronic pain bladder",
  "clenched fist overlapping finger",
  "close object appear blurry",
  "clumsy",
  "cm lump skin",
  "cold sweat",
  "coma",
  "confused thinking",
  "confusion",
  "constipation",
  "coolness",
  "coordination",
  "cough bloody mucus",
  "cough sputum production",
  "coughing",
  "coughing blood",
  "coughing including coughing blood",
  "coughing mucus",
  "crawl",
  "cry episode",
  "dark urine",
  "darker",
  "daytime sleepiness",
  "death child le one year age",
  "decreased ability feel pain",
  "decreased ability see",
  "decreased ability think",
  "decreased ability think remember",
  "decreased ability turn",
  "decreased appetite",
  "decreased motivation",
  "decreased range motion",
  "decreased taste",
  "decreased vision",
  "dehydration",
  "delayed physical growth",
  "delirium",
  "delusion",
  "dementia",
  "depending subtype abdominal pain",
  "depends organ involved",
  "depressed mood",
  "depression",
  "dermatitis herpetiformis",
  "developmental disability",
  "diarrhea",
  "diarrhea may bloody",
  "diarrhea mixed blood",
  "diarrhoea",
  "difficulty breathing",
  "difficulty cutting",
  "difficulty eating",
  "difficulty getting pregnant",
  "difficulty remembering recent event",
  "difficulty swallowing",
  "difficulty walking",
  "dimpling skin",
  "discharge penis",
  "disorientation",
  "distant object appear blurry",
  "distorted blurred vision distance",
  "dizziness",
  "double vision",
  "drinking large amount alcohol long period",
  "drooping eyelid",
  "dry cough",
  "dry damp skin",
  "dry eye",
  "dry mouth",
  "ear pain",
  "easy prolonged bleeding",
  "emotional problem",
  "enlarged lymph node neck",
  "enlarged spleen",
  "enlarged thyroid",
  "enlargement thyroid",
  "enlargement tonsil",
  "episode severe",
  "erythema marginatum",
  "excess hair",
  "excessive amount uterine bleeding",
  "excessive daytime sleepiness",
  "excessive salivation",
  "expanding area redness site tick bite",
  "extreme sadness",
  "extremity weakness",
  "eye pain",
  "eye strain",
  "eyestrain",
  "fast heart rate",
  "fast heartbeat",
  "fatigue",
  "fear water",
  "feel need check thing repeatedly",
  "feeling cold",
  "feeling faint upon standing",
  "feeling generally unwell",
  "feeling like passing",
  "feeling need urinate right away",
  "feeling tired",
  "feeling tired time",
  "fever",
  "firm",
  "flat discolored spot bump may blister",
  "flu like illness",
  "flu like symptom",
  "fluid filled blister scab",
  "fluid nipple",
  "frequent infection",
  "frequent urination",
  "fullness",
  "gas",
  "gradual loss coordination",
  "growth delay",
  "gum disease",
  "hair loss",
  "half ring finger",
  "hallucination",
  "hallucination usually hearing voice",
  "hard swelling skin",
  "hard time reading small print",
  "headache",
  "hearing loss",
  "hearing sound external sound present",
  "heartburn",
  "heat intolerance",
  "heavy period",
  "high blood pressure",
  "high body temperature",
  "hoarse voice",
  "hold reading material farther away",
  "impaired communication",
  "inability child",
  "inability move facial muscle one side",
  "inability move feel one side body",
  "increased breath rate",
  "increased breathing rate",
  "increased fat",
  "increased heart rate",
  "increased hunger",
  "increased risk broken bone",
  "increased risk infection",
  "increased thirst",
  "increasing weakening",
  "index",
  "infertility",
  "inflamed eye",
  "insomnia",
  "intellectual disability",
  "involuntary muscle movement",
  "involuntary sleep episode",
  "irregular edge",
  "irregular menstrual period",
  "irregular menstruation",
  "irritability",
  "irritation",
  "itchiness",
  "itching",
  "itching genital area",
  "itching result trouble sleeping",
  "itchy",
  "itchy blister",
  "itchy bump",
  "itchy ear",
  "jaundice",
  "jaw",
  "jerky body movement",
  "joint bone pain",
  "joint swelling",
  "large amount watery diarrhea",
  "large forehead",
  "large lymph node",
  "large lymph node around neck",
  "leg swelling",
  "light sensitivity",
  "little pain",
  "localized breast pain redness",
  "long term fatigue",
  "loose frequent bowel movement",
  "loose teeth",
  "loss appetite",
  "loss consciousness may sweating",
  "loss hair part head body",
  "loss lot blood childbirth",
  "loss smell",
  "loss vision one side",
  "low blood pressure",
  "low energy",
  "low red blood cell",
  "lower abdominal pain",
  "lump breast",
  "lump bump neck",
  "maculopapular rash",
  "malabsorption",
  "may symptom",
  "memory problem",
  "mental ability",
  "mental change",
  "mid dilated pupil",
  "middle finger",
  "mild moderate intellectual disability",
  "minimal",
  "missed period",
  "mole increasing size",
  "mood change",
  "mood swing",
  "mouth sore",
  "mouth ulcer",
  "multiple painful joint",
  "muscle ache difficulty breathing",
  "muscle cramp",
  "muscle joint pain",
  "muscle spasm",
  "muscle weakness",
  "muscle weakness beginning foot hand",
  "muscle weakness resulting inability move",
  "muscular pain",
  "myalgia",
  "nausea",
  "nausea vomiting",
  "nausea vomiting weight loss dehydration occur",
  "nearly undetectable spell",
  "nearsightedness",
  "neck",
  "neck stiffness",
  "needing urinate often",
  "newly inverted nipple",
  "non itchy skin ulcer",
  "non painful cyst middle eyelid",
  "nonaligned eye",
  "none non specific",
  "numbness",
  "object different size eye",
  "one eye myopia eye hyperopia",
  "opening upper lip may extend nose palate",
  "others",
  "overlying redness",
  "pain along inside edge shinbone",
  "pain area",
  "pain around ear",
  "pain doesnt go shingle",
  "pain going leg lower back",
  "pain sex",
  "pain specific bone",
  "painful",
  "painful blister lower leg",
  "painful heavy period",
  "painful joint base big toe",
  "painful rash occurring stripe",
  "painful skin",
  "painful swelling parotid gland",
  "painful swollen gland",
  "pale skin",
  "palpitations",
  "paralysis",
  "part painful",
  "persistent fever",
  "persistent pain",
  "persistent vomiting",
  "pleural effusion",
  "pneumonia",
  "poor coordination",
  "poor energy",
  "poor growth",
  "poor muscle tone",
  "poor vision",
  "post nasal drip",
  "post surgery complication",
  "prickling",
  "prolonged",
  "prolonged muscle contraction",
  "prolonged shoulder pain",
  "pronounced aversion bitter food",
  "pronounced swelling",
  "quicker heart rate",
  "rapid breathing",
  "rapidly onset",
  "rash",
  "rash appears around mouth eye",
  "redness",
  "redness eye",
  "redness skin",
  "reduced vision",
  "rheumatoid arthritis",
  "rising temperature",
  "running nose",
  "scab or open sore",
  "seizure",
  "seizure disorder",
  "severe abdominal pain",
  "severe allergic reaction",
  "severe headache",
  "severe pain",
  "severe pain throughout body",
  "short attention span",
  "short stature",
  "shortness breath",
  "shoulder joint pain",
  "skin rash",
  "skin ulcer",
  "skin dryness",
  "skin peeling",
  "sleep apnea",
  "sore throat",
  "sore throat swelling",
  "sore tongue",
  "spasms leg muscle",
  "speech impairment",
  "stomach ache",
  "stomach bloating",
  "stomach pain",
  "stuffy nose",
  "sudden change vision",
  "sudden difficulty speaking",
  "sudden dizziness",
  "sudden increase thirst",
  "sudden muscle weakness",
  "sudden shortness breath",
  "swelling leg ankle",
  "swelling lip",
  "swollen abdomen",
  "swollen joint",
  "swollen lymph node",
  "swollen testicle",
  "swollen toe",
  "sweating",
  "swollen body part",
  "sweating night",
  "throat",
  "throat tightness",
  "tingling",
  "tingling fingers toes",
  "tiredness",
  "tooth pain",
  "tremors",
  "trouble breathing",
  "trouble hearing",
  "trouble sleeping",
  "trouble swallowing",
  "trouble thinking remembering",
  "uncontrollable tremor",
  "unusual bleeding",
  "unusual bruising",
  "unusual headache",
  "unusual thirst",
  "upper abdominal pain",
  "urinary incontinence",
  "urine leaking",
  "urine yellow",
  "uterine bleeding",
  "vaginal bleeding",
  "vaginal dryness",
  "vaginal itching",
  "vaginal lump",
  "vomiting",
  "weakness",
  "weight gain",
  "weight loss",
  "whistle sound breathing",
  "worsening vision"
]
